version: '3.8'

services:

  model:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env-file:
      - /ambientes/.env
    environment:
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"